### ISSUE TITLE
Project Dead?

### ISSUE THREAD

**Issue by lucassmacedo** [cybercog/laravel-notification-channel-rocket-chat#2]
Hello. This project is dead?

**Comment by antonkomarev** [comment]
Hello @lucassmacedo!

This project was created for [merging with the Laravel Notification Channels package](https://github.com/laravel-notification-channels/new-channels/issues/6#issuecomment-283767862), but this didn't happen.

It was developed while I tested integration with community rocket chat instance. We no longer use it because we've chosen another app.

If anybody wants to maintain it, I can give an access, but now development on hold.

**Comment by lucassmacedo** [comment]
Hello, I have an interest in maintaining the project. I am currently using Rocket Chat and we need this feature.

**Comment by antonkomarev** [comment]
@lucassmacedo welcome aboard! You was added to collaborators with `writer` rights, feel free to ping me if there is a need.

**Comment by antonkomarev** [comment]
I plan to push some packagist & readme changes in near future.

**Comment by lucassmacedo** [comment]
Thanks bro! I will!!

**Comment by atymic** [comment]
Hi!

Would you like to move this package under the laravel notifications channel namespace? 

Sorry for the delays, but I'm around now and can respond to PRs

https://github.com/laravel-notification-channels/new-channels/issues/62

Thanks

**Comment by antonkomarev** [comment]
Yeah, I could move it, but I cannot maintain and test it now because we've stopped using Rocket Chat.

**Comment by atymic** [comment]
Ok, no worries. @lucassmacedo are you interested in maintaining it?

**Comment by antonkomarev** [comment]
@atymic I've updated code style and cleaned up code a bit. But it needs to be tested on more modern Laravel versions.

**Comment by antonkomarev** [comment]
I cannot transfer package:
> You don’t have the permission to create public repositories on laravel-notification-channels

**Comment by Funfare** [comment]
What is now the plan for this package? Are you planning to release it and/or move it to laravel-notifications-channels? I know there is a generic webhook channel, but I want to use this package an have some optimazions in things like alias, avatar, Attachments, setting author, message styling etc.
Will send you PRs for that if you want to keep this package.

**Comment by antonkomarev** [comment]
I was wanted to move it to laravel-notification-channels but nobody responded.

**Comment by Funfare** [comment]
ok but do you still want to maintain & release it? just under your own namespace so that it is more usable than requiring dev-master.
if you are not interested in it anymore i would fork it and maintain it (and for sure keep your name on it)

**Comment by antonkomarev** [comment]
If you want - I can release it and give you rights to maintain it.

**Comment by atymic** [comment]
@antonkomarev @FunfareNico 

We'd be happy to have this package under laravel notification channels :)
Let me know and I can create a repo for you.

**Comment by antonkomarev** [comment]
@atymic create repo and give me rights to upload code there or give rights to transfer this one

**Comment by atymic** [comment]
Repo invite sent :)

**Comment by antonkomarev** [comment]
Accepted. Thank you! Will move code this evening.

**Comment by Funfare** [comment]
Nice to hear that. If you want I will support you with launching and maintaining the repo :)

**Comment by antonkomarev** [comment]
@FunfareNico your help would be appreciated.

**Comment by atymic** [comment]
@FunfareNico I've added you to the new repo :)
https://github.com/laravel-notification-channels/rocket-chat

**Comment by antonkomarev** [comment]
Project code was moved to the new repo yesterday evening. Closing this issue. This project will be archived today evening.
